// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v7.34.1
// source: internal/consensus/consensuspb/commit.proto

package consensuspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CommitCommand is the replicated record of one exactly-once commit decision,
// serialized as an entry in the Raft log. It has a schema (rather than ad-hoc
// JSON) because it is a durable, cross-process wire format that may need to evolve
// with forward/backward compatibility.
type CommitCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Generation    int64                  `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`            // lease generation; fences stale attempts
	FinalKey      string                 `protobuf:"bytes,4,opt,name=final_key,json=finalKey,proto3" json:"final_key,omitempty"` // canonical output location
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitCommand) Reset() {
	*x = CommitCommand{}
	mi := &file_internal_consensus_consensuspb_commit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitCommand) ProtoMessage() {}

func (x *CommitCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_consensus_consensuspb_commit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitCommand.ProtoReflect.Descriptor instead.
func (*CommitCommand) Descriptor() ([]byte, []int) {
	return file_internal_consensus_consensuspb_commit_proto_rawDescGZIP(), []int{0}
}

func (x *CommitCommand) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CommitCommand) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CommitCommand) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *CommitCommand) GetFinalKey() string {
	if x != nil {
		return x.FinalKey
	}
	return ""
}

var File_internal_consensus_consensuspb_commit_proto protoreflect.FileDescriptor

const file_internal_consensus_consensuspb_commit_proto_rawDesc = "" +
	"\n" +
	"+internal/consensus/consensuspb/commit.proto\x12\fconsensus.v1\"|\n" +
	"\rCommitCommand\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x03R\n" +
	"generation\x12\x1b\n" +
	"\tfinal_key\x18\x04 \x01(\tR\bfinalKeyBhZfgithub.com/AbhiramDodda/distributed-image-processing-system/internal/consensus/consensuspb;consensuspbb\x06proto3"

var (
	file_internal_consensus_consensuspb_commit_proto_rawDescOnce sync.Once
	file_internal_consensus_consensuspb_commit_proto_rawDescData []byte
)

func file_internal_consensus_consensuspb_commit_proto_rawDescGZIP() []byte {
	file_internal_consensus_consensuspb_commit_proto_rawDescOnce.Do(func() {
		file_internal_consensus_consensuspb_commit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_consensus_consensuspb_commit_proto_rawDesc), len(file_internal_consensus_consensuspb_commit_proto_rawDesc)))
	})
	return file_internal_consensus_consensuspb_commit_proto_rawDescData
}

var file_internal_consensus_consensuspb_commit_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_consensus_consensuspb_commit_proto_goTypes = []any{
	(*CommitCommand)(nil), // 0: consensus.v1.CommitCommand
}
var file_internal_consensus_consensuspb_commit_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_consensus_consensuspb_commit_proto_init() }
func file_internal_consensus_consensuspb_commit_proto_init() {
	if File_internal_consensus_consensuspb_commit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_consensus_consensuspb_commit_proto_rawDesc), len(file_internal_consensus_consensuspb_commit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_consensus_consensuspb_commit_proto_goTypes,
		DependencyIndexes: file_internal_consensus_consensuspb_commit_proto_depIdxs,
		MessageInfos:      file_internal_consensus_consensuspb_commit_proto_msgTypes,
	}.Build()
	File_internal_consensus_consensuspb_commit_proto = out.File
	file_internal_consensus_consensuspb_commit_proto_goTypes = nil
	file_internal_consensus_consensuspb_commit_proto_depIdxs = nil
}
