// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v7.34.1
// source: internal/consensus/raftgrpc/raft.proto

package raftgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RaftEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // a raftpb.Message, marshaled with google.golang.org/protobuf
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftEnvelope) Reset() {
	*x = RaftEnvelope{}
	mi := &file_internal_consensus_raftgrpc_raft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftEnvelope) ProtoMessage() {}

func (x *RaftEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_internal_consensus_raftgrpc_raft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftEnvelope.ProtoReflect.Descriptor instead.
func (*RaftEnvelope) Descriptor() ([]byte, []int) {
	return file_internal_consensus_raftgrpc_raft_proto_rawDescGZIP(), []int{0}
}

func (x *RaftEnvelope) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RaftAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftAck) Reset() {
	*x = RaftAck{}
	mi := &file_internal_consensus_raftgrpc_raft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftAck) ProtoMessage() {}

func (x *RaftAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_consensus_raftgrpc_raft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftAck.ProtoReflect.Descriptor instead.
func (*RaftAck) Descriptor() ([]byte, []int) {
	return file_internal_consensus_raftgrpc_raft_proto_rawDescGZIP(), []int{1}
}

var File_internal_consensus_raftgrpc_raft_proto protoreflect.FileDescriptor

const file_internal_consensus_raftgrpc_raft_proto_rawDesc = "" +
	"\n" +
	"&internal/consensus/raftgrpc/raft.proto\x12\vraftgrpc.v1\"\"\n" +
	"\fRaftEnvelope\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\t\n" +
	"\aRaftAck2H\n" +
	"\rRaftTransport\x127\n" +
	"\x04Step\x12\x19.raftgrpc.v1.RaftEnvelope\x1a\x14.raftgrpc.v1.RaftAckBbZ`github.com/AbhiramDodda/distributed-image-processing-system/internal/consensus/raftgrpc;raftgrpcb\x06proto3"

var (
	file_internal_consensus_raftgrpc_raft_proto_rawDescOnce sync.Once
	file_internal_consensus_raftgrpc_raft_proto_rawDescData []byte
)

func file_internal_consensus_raftgrpc_raft_proto_rawDescGZIP() []byte {
	file_internal_consensus_raftgrpc_raft_proto_rawDescOnce.Do(func() {
		file_internal_consensus_raftgrpc_raft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_consensus_raftgrpc_raft_proto_rawDesc), len(file_internal_consensus_raftgrpc_raft_proto_rawDesc)))
	})
	return file_internal_consensus_raftgrpc_raft_proto_rawDescData
}

var file_internal_consensus_raftgrpc_raft_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_consensus_raftgrpc_raft_proto_goTypes = []any{
	(*RaftEnvelope)(nil), // 0: raftgrpc.v1.RaftEnvelope
	(*RaftAck)(nil),      // 1: raftgrpc.v1.RaftAck
}
var file_internal_consensus_raftgrpc_raft_proto_depIdxs = []int32{
	0, // 0: raftgrpc.v1.RaftTransport.Step:input_type -> raftgrpc.v1.RaftEnvelope
	1, // 1: raftgrpc.v1.RaftTransport.Step:output_type -> raftgrpc.v1.RaftAck
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_consensus_raftgrpc_raft_proto_init() }
func file_internal_consensus_raftgrpc_raft_proto_init() {
	if File_internal_consensus_raftgrpc_raft_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_consensus_raftgrpc_raft_proto_rawDesc), len(file_internal_consensus_raftgrpc_raft_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_consensus_raftgrpc_raft_proto_goTypes,
		DependencyIndexes: file_internal_consensus_raftgrpc_raft_proto_depIdxs,
		MessageInfos:      file_internal_consensus_raftgrpc_raft_proto_msgTypes,
	}.Build()
	File_internal_consensus_raftgrpc_raft_proto = out.File
	file_internal_consensus_raftgrpc_raft_proto_goTypes = nil
	file_internal_consensus_raftgrpc_raft_proto_depIdxs = nil
}
