// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v7.34.1
// source: internal/rpc/coordinator.proto

package coordinatorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Timestamps are unix nanoseconds; 0 means unset. Avoids a well-known-types
// import for a field the client renders however it likes.
type Job struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Dataset          string                 `protobuf:"bytes,2,opt,name=dataset,proto3" json:"dataset,omitempty"`
	Algorithm        string                 `protobuf:"bytes,3,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Config           map[string]string      `protobuf:"bytes,4,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status           string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Shards           []string               `protobuf:"bytes,6,rep,name=shards,proto3" json:"shards,omitempty"`
	TotalTasks       int32                  `protobuf:"varint,7,opt,name=total_tasks,json=totalTasks,proto3" json:"total_tasks,omitempty"`
	DoneTasks        int32                  `protobuf:"varint,8,opt,name=done_tasks,json=doneTasks,proto3" json:"done_tasks,omitempty"`
	FailedTasks      int32                  `protobuf:"varint,9,opt,name=failed_tasks,json=failedTasks,proto3" json:"failed_tasks,omitempty"`
	CreatedAtUnixNs  int64                  `protobuf:"varint,10,opt,name=created_at_unix_ns,json=createdAtUnixNs,proto3" json:"created_at_unix_ns,omitempty"`
	StartedAtUnixNs  int64                  `protobuf:"varint,11,opt,name=started_at_unix_ns,json=startedAtUnixNs,proto3" json:"started_at_unix_ns,omitempty"`
	FinishedAtUnixNs int64                  `protobuf:"varint,12,opt,name=finished_at_unix_ns,json=finishedAtUnixNs,proto3" json:"finished_at_unix_ns,omitempty"`
	Error            string                 `protobuf:"bytes,13,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_internal_rpc_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_internal_rpc_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetDataset() string {
	if x != nil {
		return x.Dataset
	}
	return ""
}

func (x *Job) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *Job) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Job) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Job) GetShards() []string {
	if x != nil {
		return x.Shards
	}
	return nil
}

func (x *Job) GetTotalTasks() int32 {
	if x != nil {
		return x.TotalTasks
	}
	return 0
}

func (x *Job) GetDoneTasks() int32 {
	if x != nil {
		return x.DoneTasks
	}
	return 0
}

func (x *Job) GetFailedTasks() int32 {
	if x != nil {
		return x.FailedTasks
	}
	return 0
}

func (x *Job) GetCreatedAtUnixNs() int64 {
	if x != nil {
		return x.CreatedAtUnixNs
	}
	return 0
}

func (x *Job) GetStartedAtUnixNs() int64 {
	if x != nil {
		return x.StartedAtUnixNs
	}
	return 0
}

func (x *Job) GetFinishedAtUnixNs() int64 {
	if x != nil {
		return x.FinishedAtUnixNs
	}
	return 0
}

func (x *Job) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TaskAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Shard         string                 `protobuf:"bytes,3,opt,name=shard,proto3" json:"shard,omitempty"`
	Dataset       string                 `protobuf:"bytes,4,opt,name=dataset,proto3" json:"dataset,omitempty"`
	Algorithm     string                 `protobuf:"bytes,5,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Config        map[string]string      `protobuf:"bytes,6,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskAssignment) Reset() {
	*x = TaskAssignment{}
	mi := &file_internal_rpc_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAssignment) ProtoMessage() {}

func (x *TaskAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAssignment.ProtoReflect.Descriptor instead.
func (*TaskAssignment) Descriptor() ([]byte, []int) {
	return file_internal_rpc_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *TaskAssignment) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskAssignment) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *TaskAssignment) GetShard() string {
	if x != nil {
		return x.Shard
	}
	return ""
}

func (x *TaskAssignment) GetDataset() string {
	if x != nil {
		return x.Dataset
	}
	return ""
}

func (x *TaskAssignment) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *TaskAssignment) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type SubmitJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dataset       string                 `protobuf:"bytes,1,opt,name=dataset,proto3" json:"dataset,omitempty"`
	Algorithm     string                 `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Config        map[string]string      `protobuf:"bytes,3,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Shards        []string               `protobuf:"bytes,4,rep,name=shards,proto3" json:"shards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobRequest) Reset() {
	*x = SubmitJobRequest{}
	mi := &file_internal_rpc_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobRequest) ProtoMessage() {}

func (x *SubmitJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobRequest.ProtoReflect.Descriptor instead.
func (*SubmitJobRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitJobRequest) GetDataset() string {
	if x != nil {
		return x.Dataset
	}
	return ""
}

func (x *SubmitJobRequest) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *SubmitJobRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *SubmitJobRequest) GetShards() []string {
	if x != nil {
		return x.Shards
	}
	return nil
}

type SubmitJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	TotalTasks    int32                  `protobuf:"varint,2,opt,name=total_tasks,json=totalTasks,proto3" json:"total_tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobResponse) Reset() {
	*x = SubmitJobResponse{}
	mi := &file_internal_rpc_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobResponse) ProtoMessage() {}

func (x *SubmitJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobResponse.ProtoReflect.Descriptor instead.
func (*SubmitJobResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_coordinator_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SubmitJobResponse) GetTotalTasks() int32 {
	if x != nil {
		return x.TotalTasks
	}
	return 0
}

type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_internal_rpc_coordinator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_coordinator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_coordinator_proto_rawDescGZIP(), []int{4}
}

func (x *GetJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type ListJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_internal_rpc_coordinator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_coordinator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_coordinator_proto_rawDescGZIP(), []int{5}
}

type ListJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*Job                 `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_internal_rpc_coordinator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_coordinator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_coordinator_proto_rawDescGZIP(), []int{6}
}

func (x *ListJobsResponse) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type PollTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollTasksRequest) Reset() {
	*x = PollTasksRequest{}
	mi := &file_internal_rpc_coordinator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollTasksRequest) ProtoMessage() {}

func (x *PollTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_coordinator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollTasksRequest.ProtoReflect.Descriptor instead.
func (*PollTasksRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_coordinator_proto_rawDescGZIP(), []int{7}
}

func (x *PollTasksRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type PollTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assignment    *TaskAssignment        `protobuf:"bytes,1,opt,name=assignment,proto3" json:"assignment,omitempty"`
	HasWork       bool                   `protobuf:"varint,2,opt,name=has_work,json=hasWork,proto3" json:"has_work,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollTasksResponse) Reset() {
	*x = PollTasksResponse{}
	mi := &file_internal_rpc_coordinator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollTasksResponse) ProtoMessage() {}

func (x *PollTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_coordinator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollTasksResponse.ProtoReflect.Descriptor instead.
func (*PollTasksResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_coordinator_proto_rawDescGZIP(), []int{8}
}

func (x *PollTasksResponse) GetAssignment() *TaskAssignment {
	if x != nil {
		return x.Assignment
	}
	return nil
}

func (x *PollTasksResponse) GetHasWork() bool {
	if x != nil {
		return x.HasWork
	}
	return false
}

type StartTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTaskRequest) Reset() {
	*x = StartTaskRequest{}
	mi := &file_internal_rpc_coordinator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTaskRequest) ProtoMessage() {}

func (x *StartTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_coordinator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTaskRequest.ProtoReflect.Descriptor instead.
func (*StartTaskRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_coordinator_proto_rawDescGZIP(), []int{9}
}

func (x *StartTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StartTaskRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type StartTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTaskResponse) Reset() {
	*x = StartTaskResponse{}
	mi := &file_internal_rpc_coordinator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTaskResponse) ProtoMessage() {}

func (x *StartTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_coordinator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTaskResponse.ProtoReflect.Descriptor instead.
func (*StartTaskResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_coordinator_proto_rawDescGZIP(), []int{10}
}

type ReportResultRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskId          string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkerId        string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	ImagesProcessed int64                  `protobuf:"varint,3,opt,name=images_processed,json=imagesProcessed,proto3" json:"images_processed,omitempty"`
	BytesRead       int64                  `protobuf:"varint,4,opt,name=bytes_read,json=bytesRead,proto3" json:"bytes_read,omitempty"`
	OutputKey       string                 `protobuf:"bytes,5,opt,name=output_key,json=outputKey,proto3" json:"output_key,omitempty"`
	DurationNs      int64                  `protobuf:"varint,6,opt,name=duration_ns,json=durationNs,proto3" json:"duration_ns,omitempty"`
	Error           string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReportResultRequest) Reset() {
	*x = ReportResultRequest{}
	mi := &file_internal_rpc_coordinator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultRequest) ProtoMessage() {}

func (x *ReportResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_coordinator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultRequest.ProtoReflect.Descriptor instead.
func (*ReportResultRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_coordinator_proto_rawDescGZIP(), []int{11}
}

func (x *ReportResultRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ReportResultRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *ReportResultRequest) GetImagesProcessed() int64 {
	if x != nil {
		return x.ImagesProcessed
	}
	return 0
}

func (x *ReportResultRequest) GetBytesRead() int64 {
	if x != nil {
		return x.BytesRead
	}
	return 0
}

func (x *ReportResultRequest) GetOutputKey() string {
	if x != nil {
		return x.OutputKey
	}
	return ""
}

func (x *ReportResultRequest) GetDurationNs() int64 {
	if x != nil {
		return x.DurationNs
	}
	return 0
}

func (x *ReportResultRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReportResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultResponse) Reset() {
	*x = ReportResultResponse{}
	mi := &file_internal_rpc_coordinator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultResponse) ProtoMessage() {}

func (x *ReportResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_coordinator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultResponse.ProtoReflect.Descriptor instead.
func (*ReportResultResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_coordinator_proto_rawDescGZIP(), []int{12}
}

type WatchJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchJobRequest) Reset() {
	*x = WatchJobRequest{}
	mi := &file_internal_rpc_coordinator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchJobRequest) ProtoMessage() {}

func (x *WatchJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_coordinator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchJobRequest.ProtoReflect.Descriptor instead.
func (*WatchJobRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_coordinator_proto_rawDescGZIP(), []int{13}
}

func (x *WatchJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

var File_internal_rpc_coordinator_proto protoreflect.FileDescriptor

const file_internal_rpc_coordinator_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/rpc/coordinator.proto\x12\x0ecoordinator.v1\"\xf3\x03\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\adataset\x18\x02 \x01(\tR\adataset\x12\x1c\n" +
	"\talgorithm\x18\x03 \x01(\tR\talgorithm\x127\n" +
	"\x06config\x18\x04 \x03(\v2\x1f.coordinator.v1.Job.ConfigEntryR\x06config\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x16\n" +
	"\x06shards\x18\x06 \x03(\tR\x06shards\x12\x1f\n" +
	"\vtotal_tasks\x18\a \x01(\x05R\n" +
	"totalTasks\x12\x1d\n" +
	"\n" +
	"done_tasks\x18\b \x01(\x05R\tdoneTasks\x12!\n" +
	"\ffailed_tasks\x18\t \x01(\x05R\vfailedTasks\x12+\n" +
	"\x12created_at_unix_ns\x18\n" +
	" \x01(\x03R\x0fcreatedAtUnixNs\x12+\n" +
	"\x12started_at_unix_ns\x18\v \x01(\x03R\x0fstartedAtUnixNs\x12-\n" +
	"\x13finished_at_unix_ns\x18\f \x01(\x03R\x10finishedAtUnixNs\x12\x14\n" +
	"\x05error\x18\r \x01(\tR\x05error\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8d\x02\n" +
	"\x0eTaskAssignment\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05shard\x18\x03 \x01(\tR\x05shard\x12\x18\n" +
	"\adataset\x18\x04 \x01(\tR\adataset\x12\x1c\n" +
	"\talgorithm\x18\x05 \x01(\tR\talgorithm\x12B\n" +
	"\x06config\x18\x06 \x03(\v2*.coordinator.v1.TaskAssignment.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe3\x01\n" +
	"\x10SubmitJobRequest\x12\x18\n" +
	"\adataset\x18\x01 \x01(\tR\adataset\x12\x1c\n" +
	"\talgorithm\x18\x02 \x01(\tR\talgorithm\x12D\n" +
	"\x06config\x18\x03 \x03(\v2,.coordinator.v1.SubmitJobRequest.ConfigEntryR\x06config\x12\x16\n" +
	"\x06shards\x18\x04 \x03(\tR\x06shards\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"K\n" +
	"\x11SubmitJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1f\n" +
	"\vtotal_tasks\x18\x02 \x01(\x05R\n" +
	"totalTasks\"&\n" +
	"\rGetJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x11\n" +
	"\x0fListJobsRequest\";\n" +
	"\x10ListJobsResponse\x12'\n" +
	"\x04jobs\x18\x01 \x03(\v2\x13.coordinator.v1.JobR\x04jobs\"/\n" +
	"\x10PollTasksRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"n\n" +
	"\x11PollTasksResponse\x12>\n" +
	"\n" +
	"assignment\x18\x01 \x01(\v2\x1e.coordinator.v1.TaskAssignmentR\n" +
	"assignment\x12\x19\n" +
	"\bhas_work\x18\x02 \x01(\bR\ahasWork\"H\n" +
	"\x10StartTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\"\x13\n" +
	"\x11StartTaskResponse\"\xeb\x01\n" +
	"\x13ReportResultRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12)\n" +
	"\x10images_processed\x18\x03 \x01(\x03R\x0fimagesProcessed\x12\x1d\n" +
	"\n" +
	"bytes_read\x18\x04 \x01(\x03R\tbytesRead\x12\x1d\n" +
	"\n" +
	"output_key\x18\x05 \x01(\tR\toutputKey\x12\x1f\n" +
	"\vduration_ns\x18\x06 \x01(\x03R\n" +
	"durationNs\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"\x16\n" +
	"\x14ReportResultResponse\"(\n" +
	"\x0fWatchJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId2\xaf\x04\n" +
	"\vCoordinator\x12P\n" +
	"\tSubmitJob\x12 .coordinator.v1.SubmitJobRequest\x1a!.coordinator.v1.SubmitJobResponse\x12<\n" +
	"\x06GetJob\x12\x1d.coordinator.v1.GetJobRequest\x1a\x13.coordinator.v1.Job\x12M\n" +
	"\bListJobs\x12\x1f.coordinator.v1.ListJobsRequest\x1a .coordinator.v1.ListJobsResponse\x12P\n" +
	"\tPollTasks\x12 .coordinator.v1.PollTasksRequest\x1a!.coordinator.v1.PollTasksResponse\x12P\n" +
	"\tStartTask\x12 .coordinator.v1.StartTaskRequest\x1a!.coordinator.v1.StartTaskResponse\x12Y\n" +
	"\fReportResult\x12#.coordinator.v1.ReportResultRequest\x1a$.coordinator.v1.ReportResultResponse\x12B\n" +
	"\bWatchJob\x12\x1f.coordinator.v1.WatchJobRequest\x1a\x13.coordinator.v1.Job0\x01BPZNgithub.com/abhiramd/petabyte-platform/internal/rpc/coordinatorpb;coordinatorpbb\x06proto3"

var (
	file_internal_rpc_coordinator_proto_rawDescOnce sync.Once
	file_internal_rpc_coordinator_proto_rawDescData []byte
)

func file_internal_rpc_coordinator_proto_rawDescGZIP() []byte {
	file_internal_rpc_coordinator_proto_rawDescOnce.Do(func() {
		file_internal_rpc_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_rpc_coordinator_proto_rawDesc), len(file_internal_rpc_coordinator_proto_rawDesc)))
	})
	return file_internal_rpc_coordinator_proto_rawDescData
}

var file_internal_rpc_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_internal_rpc_coordinator_proto_goTypes = []any{
	(*Job)(nil),                  // 0: coordinator.v1.Job
	(*TaskAssignment)(nil),       // 1: coordinator.v1.TaskAssignment
	(*SubmitJobRequest)(nil),     // 2: coordinator.v1.SubmitJobRequest
	(*SubmitJobResponse)(nil),    // 3: coordinator.v1.SubmitJobResponse
	(*GetJobRequest)(nil),        // 4: coordinator.v1.GetJobRequest
	(*ListJobsRequest)(nil),      // 5: coordinator.v1.ListJobsRequest
	(*ListJobsResponse)(nil),     // 6: coordinator.v1.ListJobsResponse
	(*PollTasksRequest)(nil),     // 7: coordinator.v1.PollTasksRequest
	(*PollTasksResponse)(nil),    // 8: coordinator.v1.PollTasksResponse
	(*StartTaskRequest)(nil),     // 9: coordinator.v1.StartTaskRequest
	(*StartTaskResponse)(nil),    // 10: coordinator.v1.StartTaskResponse
	(*ReportResultRequest)(nil),  // 11: coordinator.v1.ReportResultRequest
	(*ReportResultResponse)(nil), // 12: coordinator.v1.ReportResultResponse
	(*WatchJobRequest)(nil),      // 13: coordinator.v1.WatchJobRequest
	nil,                          // 14: coordinator.v1.Job.ConfigEntry
	nil,                          // 15: coordinator.v1.TaskAssignment.ConfigEntry
	nil,                          // 16: coordinator.v1.SubmitJobRequest.ConfigEntry
}
var file_internal_rpc_coordinator_proto_depIdxs = []int32{
	14, // 0: coordinator.v1.Job.config:type_name -> coordinator.v1.Job.ConfigEntry
	15, // 1: coordinator.v1.TaskAssignment.config:type_name -> coordinator.v1.TaskAssignment.ConfigEntry
	16, // 2: coordinator.v1.SubmitJobRequest.config:type_name -> coordinator.v1.SubmitJobRequest.ConfigEntry
	0,  // 3: coordinator.v1.ListJobsResponse.jobs:type_name -> coordinator.v1.Job
	1,  // 4: coordinator.v1.PollTasksResponse.assignment:type_name -> coordinator.v1.TaskAssignment
	2,  // 5: coordinator.v1.Coordinator.SubmitJob:input_type -> coordinator.v1.SubmitJobRequest
	4,  // 6: coordinator.v1.Coordinator.GetJob:input_type -> coordinator.v1.GetJobRequest
	5,  // 7: coordinator.v1.Coordinator.ListJobs:input_type -> coordinator.v1.ListJobsRequest
	7,  // 8: coordinator.v1.Coordinator.PollTasks:input_type -> coordinator.v1.PollTasksRequest
	9,  // 9: coordinator.v1.Coordinator.StartTask:input_type -> coordinator.v1.StartTaskRequest
	11, // 10: coordinator.v1.Coordinator.ReportResult:input_type -> coordinator.v1.ReportResultRequest
	13, // 11: coordinator.v1.Coordinator.WatchJob:input_type -> coordinator.v1.WatchJobRequest
	3,  // 12: coordinator.v1.Coordinator.SubmitJob:output_type -> coordinator.v1.SubmitJobResponse
	0,  // 13: coordinator.v1.Coordinator.GetJob:output_type -> coordinator.v1.Job
	6,  // 14: coordinator.v1.Coordinator.ListJobs:output_type -> coordinator.v1.ListJobsResponse
	8,  // 15: coordinator.v1.Coordinator.PollTasks:output_type -> coordinator.v1.PollTasksResponse
	10, // 16: coordinator.v1.Coordinator.StartTask:output_type -> coordinator.v1.StartTaskResponse
	12, // 17: coordinator.v1.Coordinator.ReportResult:output_type -> coordinator.v1.ReportResultResponse
	0,  // 18: coordinator.v1.Coordinator.WatchJob:output_type -> coordinator.v1.Job
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_internal_rpc_coordinator_proto_init() }
func file_internal_rpc_coordinator_proto_init() {
	if File_internal_rpc_coordinator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_rpc_coordinator_proto_rawDesc), len(file_internal_rpc_coordinator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_rpc_coordinator_proto_goTypes,
		DependencyIndexes: file_internal_rpc_coordinator_proto_depIdxs,
		MessageInfos:      file_internal_rpc_coordinator_proto_msgTypes,
	}.Build()
	File_internal_rpc_coordinator_proto = out.File
	file_internal_rpc_coordinator_proto_goTypes = nil
	file_internal_rpc_coordinator_proto_depIdxs = nil
}
